export const FLOW_ENUM = {
    START_GAME: "START_GAME",
    SELECT_WAY_IN: "SELECT_WAY_IN",
    SELECT_ROAD: "SELECT_ROAD",
    SELECT_ROAD_TO_VALORILA: "SELECT_ROAD_TO_VALORILA",
    SELECT_POWER_PERCENTAGE: "SELECT_POWER_PERCENTAGE",
    INCREASE_SOLDIERS: "INCREASE_SOLDIERS",
    CHOOSE_FIVE_LEADERS: "CHOOSE_FIVE_LEADERS",
    WARNING_ATTACK_GATES: "WARNING_ATTACK_GATES",
    CHANGE_ROAD: "CHANGE_ROAD",
    SHOW_VAL_MAP: "SHOW_VAL_MAP"
} as const

export type FLOW_ENUM = (typeof FLOW_ENUM)[keyof typeof FLOW_ENUM]
